### PR TITLE
Fix double unref issue when using signal callback

### PR DESCRIPTION
**Pull request by awarecan**
Fix https://github.com/facebookincubator/pystemd/issues/7#issuecomment-398924831

### CODE REVIEW

**Comment by awarecan** [comment]
CLA signed

**Comment by awarecan** [comment]
CI had failed on master...

**Comment by davide125** [comment]
CI failure is unrelated, it's failing in master as well -- the version of systemd we have in Travis is too old

**Comment by aleivag** [comment]
Hey Thanks for submitting code, we really apreciate when people take their time to collaborate. and yeap, i need to fix travis, because i would like to make test to verify that we dont break you. 

Please also see my comment in issue #7 about how there is another solution for this...

thanks

**Comment by aleivag** [comment]
this was addressed already, and no further discussion has been make

**Pull request closed without merging**
